namespace: grupp4
images:
  backend:
    repository: ghcr.io/bathrobebat/backend
    tag: "5400eaa"
  frontend:
    repository: ghcr.io/bathrobebat/frontend
    tag: "5400eaa"
  postgres: "quay.io/fedora/postgresql-16:latest"
  redis: "quay.io/kurs/redis:latest"
imagePullPolicy: IfNotPresent
replicas:
  backend: 2
  frontend: 2
storage:
  postgresSize: 1Gi
  redisSize: 1Gi
db:
  name: thed-guestbook
route:
  enabled: true
  host: "" # l√•t OpenShift generera host
  tls:
    enabled: true
    termination: edge
