namespace: grupp4

images:
  backend: "ghcr.io/bathrobebat/backend-DEV"
  frontend: "ghcr.io/bathrobebat/frontend-DEV"
  postgres: "quay.io/fedora/postgresql-16:latest"
  redis: "quay.io/kurs/redis:latest"

imagePullPolicy: IfNotPresent

replicas:
  backend: 2
  frontend: 2

storage:
  postgresSize: 1Gi
  redisSize: 1Gi

db:
  name: thed-guestbook

route:
  enabled: true
  host: ""   # l√•t OpenShift generera host
  tls:
    enabled: true
    termination: edge
