apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: {{ include "guestbook.namespace" . }}
data:
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_NAME: "{{ .Values.db.name }}"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
