{{- if .Values.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: thed-guestbook
  namespace: {{ include "guestbook.namespace" . }}
  annotations:
    cert-manager.io/issuer-kind: ClusterIssuer
    cert-manager.io/issuer-name: letsencrypt-prod
spec:
  to:
    kind: Service
    name: frontend
  port:
    targetPort: 8080
  {{- if .Values.route.host }}
  host: "{{ .Values.route.host }}"
  {{- end }}
  {{- if .Values.route.tls.enabled }}
  tls:
    termination: edge
  {{- end }}
{{- end }}
